-d C:\Users\kuroc\Downloads\cpu\impl\gwsynthesis\cpu.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\kuroc\Downloads\cpu\src\cpu.cst
-cfg C:\Users\kuroc\Downloads\cpu\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
